# Generated by Django 4.1.3 on 2022-11-13 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='place',
            field=models.CharField(max_length=61),
        ),
    ]
