# Generated by Django 4.1.3 on 2022-11-13 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_alter_appointment_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='room_number',
            new_name='vechilenum',
        ),
    ]
